apiVersion: v1
kind: Service
metadata:
  name: transactions-test-svc
spec:
  type: LoadBalancer
  selector:
    app: transactions-test
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 9000 # Port on the container
